version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "9229:9229"  
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run-script dev
    environment:
      PORT: 5000